#!/bin/sh
# this should be run as the TP_USER user

PYTHON=python
PYTHONPATH="$HOME" ; export PYTHONPATH
DJANGO_SETTINGS_MODULE="project.settings_local" ; export DJANGO_SETTINGS_MODULE

. ~/bin/activate

cd ~

$PYTHON manage.py stop_stream >> "/var/log/teamplayer/teamplayer.log" 
[ -f "TP_DB/tps.pid" ] && kill $(cat "TP_DB/tps.pid")
[ -f "TP_DB/uwsgi.pid" ] && kill $(cat "TP_DB/uwsgi.pid")

