#!/bin/sh

CHROOT="$1"
APPLIANCE="`dirname $0`"

# Copy modified kdm config files
cp "$APPLIANCE"/kdmrc "$APPLIANCE"/Xaccess "$CHROOT"/usr/share/config/kdm

# enable hal
chroot "$CHROOT" rc-update add dbus default

# enable kdm
if [ -e "$CHROOT"/etc/conf.d/xdm ] ; then
    sed -i 's/^DISPLAYMANAGER=.*/DISPLAYMANAGER="kdm"/' "$CHROOT"/etc/conf.d/xdm
    chroot "$CHROOT" rc-update add xdm default
else
    echo "/usr/bin/kdm -daemon" >> "$CHROOT"/etc/conf.d/local.start
fi
