#!/bin/sh -ev

CHROOT="$1"
APPLIANCE="`dirname $0`"

# set up apache modules in make.conf
cat >> ${CHROOT}/etc/make.conf << EOF

# Apache config for TeamPlayer
APACHE2_MPMS="prefork"
APACHE2_MODULES="authz_host dir mime proxy proxy_http"
EOF

