#!/bin/sh
# this should be run as the TP_USER user

PYTHONPATH="/etc/teamplayer:$PYTHONPATH"
export PYTHONPATH

cd ~
hg serve -p 8000 --prefix /repo/ > /var/log/teamplayer/hgserve.log 2>&1 &

cd ~/web

if [ ! -f "/etc/firstboot" ] ; then
    python manage.py syncdb
fi

# spin!
python manage.py spin --verbosity=2 $@ > "/var/log/teamplayer/teamplayer.log" 2>&1 &
echo $! > "TP_DB/tps.pid"
