#!/bin/sh
# this should be run as the TP_USER user

cd ~/web
PYTHONPATH="/etc/teamplayer:$PYTHONPATH"
PYTHON=python2.7

export PYTHONPATH

[ -f "TP_DB/tps.pid" ] && kill $(cat "TP_DB/tps.pid")
[ -f "TP_DB/fcgi.pid" ] && kill $(cat "TP_DB/fcgi.pid")
$PYTHON manage.py stop_stream >> "/var/log/teamplayer/teamplayer.log" 
