#!/bin/sh
# this should be run as the TP_USER user

cd ~/web
PYTHONPATH="/etc/teamplayer:$PYTHONPATH"

export PYTHONPATH

[ -f "TP_DB/tps.pid" ] && kill $(cat "TP_DB/tps.pid")
[ -f "TP_DB/fcgi.pid" ] && kill $(cat "TP_DB/fcgi.pid")
python manage.py stop_stream >> "/var/log/teamplayer/teamplayer.log" 
