#!/bin/sh
# this should be run as the TP_USER user

PYTHON=python
DJANGO_SETTINGS_MODULE="project.settings_local" ; export DJANGO_SETTINGS_MODULE

. ~/bin/activate

cd ~

#[ -f "TP_DB/tps.pid" ] && kill $(cat "TP_DB/tps.pid")
[ -f "TP_DB/fcgi.pid" ] && kill $(cat "TP_DB/fcgi.pid")

$PYTHON manage.py stop_stream >> "/var/log/teamplayer/teamplayer.log" 
