#!/bin/sh

CHROOT="$1"
APPLIANCE="`dirname $0`"

rm -f "${CHROOT}"/var/lib/dbus/machine-id
cp "${APPLIANCE}"/custom.conf "${CHROOT}"/etc/X11/gdm/custom.conf

chroot "${CHROOT}" rc-update add hald default
echo 'gdm &>/dev/null' >> "${CHROOT}"/etc/conf.d/local.start
