
AIRPORT = {
    'GAME_NAME': 'Airport Europe',
    'SCALE_FLIGHT_TIMES': False,
    'GAMESERVER_MULTIPROCESSING': True,
    'CRUISE_SPEED': 13.0,
    'GAMESERVER_LOOP_DELAY': 3,
    'MAP_INITIAL_LATITUDE': 53.58,
    'MAP_INITIAL_LONGITUDE': 23.11,
}
